os:
  - linux
dist: trusty
sudo: false
language: c

before_script: # Get vita-gcc first (for `make tests` purpose)
  - curl -sL github.com/vitasdk/autobuilds/releases | grep linux | grep tar.bz2 | head -n 1 | cut -d '"' -f 2 | xargs -I PATH curl -sL github.comPATH | tar xj
  - export VITASDK=$PWD/vitasdk
  - export PATH=$VITASDK/bin:$PATH

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON .. # Build with coverage (`make test` purpose)
  - make all test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    - $IRC_CHANNEL
