os:
  - linux
sudo: false # faster build
language: c

before_script: # Get vita-gcc (`make tests` purpose)
  - curl https://api.github.com/repos/vitasdk/autobuilds/releases | grep browser_download_url | grep linux | head -n 1 | cut -d '"' -f 4 | xargs curl -L | tar xj
  - export VITASDK=$PWD/vitasdk
  - export PATH=$VITASDK/bin:$PATH

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON .. # Build with coverage (`make test` purpose)
  - make all test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    - "chat.freenode.net#vitasdk"
