#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "vita-import.h"

void usage();
int generate_assembly(vita_imports_t *imports);
int generate_makefile(vita_imports_t *imports);

int main(int argc, char *argv[])
{
	if (argc < 3) {
		usage();
		goto exit_failure;
	}

	vita_imports_t *imports = vita_imports_load(argv[1], 1);

	if (imports == NULL) {
		goto exit_failure;
	}

	if (chdir(argv[2])) {
		perror(argv[2]);
		goto exit_failure;
	}

	if (!generate_assembly(imports)) {
		fprintf(stderr, "Error generating the assembly file\n");
		goto exit_failure;
	}

	if (!generate_makefile(imports)) {
		fprintf(stderr, "Error generating the assembly makefile\n");
		goto exit_failure;
	}

	vita_imports_free(imports);

	return EXIT_SUCCESS;
exit_failure:
	return EXIT_FAILURE;
}


int generate_assembly(vita_imports_t *imports)
{
	char filename[128];
	FILE *fp;
	int i, j, k;

	for (i = 0; i < imports->n_libs; i++) {

		for (j = 0; j < imports->libs[i]->n_modules; j++) {

			snprintf(filename, 128, "%s.S", imports->libs[i]->modules[j]->name);

			if ((fp = fopen(filename, "w")) == NULL) {
				return 0;
			}

			fprintf(fp, "@ this file was automagically generated by vita-libs-gen by xerpi\n\n");
			fprintf(fp, "@ library: %s\n", imports->libs[i]->name);
			fprintf(fp, "@ module:  %s\n\n", imports->libs[i]->modules[j]->name);
			fprintf(fp, ".arch armv7a\n\n");

			if (imports->libs[i]->modules[j]->n_functions > 0)
				fprintf(fp, ".section .vitalink.fstubs,\"ax\",%%progbits\n\n");

			for (k = 0; k < imports->libs[i]->modules[j]->n_functions; k++) {

				const char *fname = imports->libs[i]->modules[j]->functions[k]->name;
				fprintf(fp,
					"\t.align 4\n"
					"\t.global %s\n"
					"\t.type %s, %%function\n"
					"%s:\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n\n",
					fname, fname, fname,
					imports->libs[i]->NID,
					imports->libs[i]->modules[j]->NID,
					imports->libs[i]->modules[j]->functions[k]->NID);
			}
			fprintf(fp, "\n");

			if (imports->libs[i]->modules[j]->n_variables > 0)
				fprintf(fp, ".section .vitalink.vstubs,\"awx\",%%progbits\n\n");

			for (k = 0; k < imports->libs[i]->modules[j]->n_variables; k++) {

				const char *vname = imports->libs[i]->modules[j]->variables[k]->name;
				fprintf(fp,
					"\t.align 4\n"
					"\t.global %s\n"
					"\t.type %s, %%object\n"
					"%s:\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n\n",
					vname, vname, vname,
					imports->libs[i]->NID,
					imports->libs[i]->modules[j]->NID,
					imports->libs[i]->modules[j]->variables[k]->NID);
			}

			fprintf(fp, "@ end of the file\n");
			fclose(fp);
		}
	}

	return 1;
}

int generate_makefile(vita_imports_t *imports)
{
	FILE *fp;
	int i, j;

	if ((fp = fopen("Makefile", "w")) == NULL) {
		return 0;
	}

	fputs(
		"ARCH = arm-none-eabi\n"
		"CC = $(ARCH)-gcc\n"
		"AR = $(ARCH)-ar\n"
		"RANLIB = $(ARCH)-ranlib\n\n"
		"CFLAGS =\n\n"
		"TARGETS =", fp);

	for (i = 0; i < imports->n_libs; i++) {
		fprintf(fp, " lib%s.a", imports->libs[i]->name);
	}

	fprintf(fp, "\n\n");

	for (i = 0; i < imports->n_libs; i++) {
		fprintf(fp, "%s_OBJS =", imports->libs[i]->name);

		for (j = 0; j < imports->libs[i]->n_modules; j++) {
			fprintf(fp, " %s.o", imports->libs[i]->modules[j]->name);
		}

		fprintf(fp, "\n");
	}

	fputs(
		"ALL_OBJS=\n\n"
		"define LIBRARY_template =\n"
		" $(1): $$($(1:lib%.a=%)_OBJS)\n"
		" ALL_OBJS += $$($(1:lib%.a=%)_OBJS)\n"
		"endef\n\n"
		"$(foreach library,$(TARGETS),$(eval $(call LIBRARY_template,$(library))))\n\n"
		"all: $(TARGETS)\n\n"
		"clean:\n\n"
		"\trm -f $(TARGETS) $(ALL_OBJS)\n\n"
		"$(TARGETS):\n"
		"\t$(AR) cru $@ $?\n"
		"\t$(RANLIB) $@\n\n"
		"%.o: %.S\n"
		"\t$(CC) $(CFLAGS) -c $< -o $@\n"
		, fp);

	fclose(fp);

	return 1;
}

void usage()
{
	fprintf(stderr,
		"vita-libs-gen by xerpi\n"
		"usage:\n\tvita-libs-gen nids.json output-dir\n"
	);
}
