#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include "vita-import.h"

#define KERNEL_LIBS_STUB "SceKernel"

void usage();
int generate_assembly(vita_imports_t *imports);
int generate_makefile(vita_imports_t *imports);

int main(int argc, char *argv[])
{
	if (argc < 3) {
		usage();
		goto exit_failure;
	}

	vita_imports_t *imports = vita_imports_load(argv[1], 1);

	if (imports == NULL) {
		goto exit_failure;
	}

	if (chdir(argv[2])) {
		perror(argv[2]);
		goto exit_failure;
	}

	if (!generate_assembly(imports)) {
		fprintf(stderr, "Error generating the assembly file\n");
		goto exit_failure;
	}

	if (!generate_makefile(imports)) {
		fprintf(stderr, "Error generating the assembly makefile\n");
		goto exit_failure;
	}

	vita_imports_free(imports);

	return EXIT_SUCCESS;
exit_failure:
	return EXIT_FAILURE;
}


int generate_assembly(vita_imports_t *imports)
{
	char filename[128];
	FILE *fp;
	int i, j, k;

	for (i = 0; i < imports->n_libs; i++) {
		vita_imports_lib_t *library = imports->libs[i];
		for (j = 0; j < library->n_modules; j++) {
			vita_imports_module_t *module = library->modules[j];
			snprintf(filename, sizeof(filename), "%s.S", module->name);

			if ((fp = fopen(filename, "w")) == NULL) {
				return 0;
			}

			fprintf(fp, "@ this file was automagically generated by vita-libs-gen by xerpi\n\n");
			fprintf(fp, "@ library: %s\n", library->name);
			fprintf(fp, "@ module:  %s\n\n", module->name);
			fprintf(fp, ".arch armv7a\n\n");

			if (module->n_functions > 0)
				fprintf(fp, ".section .vitalink.fstubs,\"ax\",%%progbits\n\n");

			for (k = 0; k < module->n_functions; k++) {
				vita_imports_stub_t *function = module->functions[k];
				const char *fname = function->name;
				fprintf(fp,
					"\t.align 4\n"
					"\t.global %s\n"
					"\t.type %s, %%function\n"
					"%s:\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n\n",
					fname, fname, fname,
					library->NID,
					module->NID,
					function->NID);
			}
			fprintf(fp, "\n");

			if (module->n_variables > 0)
				fprintf(fp, ".section .vitalink.vstubs,\"aw\",%%progbits\n\n");

			for (k = 0; k < module->n_variables; k++) {
				vita_imports_stub_t *variable = module->variables[k];
				const char *vname = variable->name;
				fprintf(fp,
					"\t.align 4\n"
					"\t.global %s\n"
					"\t.type %s, %%object\n"
					"%s:\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n"
					"\t.word 0x%08X\n\n",
					vname, vname, vname,
					library->NID,
					module->NID,
					variable->NID);
			}

			fprintf(fp, "@ end of the file\n");
			fclose(fp);
		}
	}

	return 1;
}

int generate_makefile(vita_imports_t *imports)
{
	FILE *fp;
	int i, j, k;
	char *kernel_objs, *tmp;
	size_t size, written;
	int is_special;

	if ((fp = fopen("Makefile", "w")) == NULL) {
		return 0;
	}

	size = 1024;
	written = 0;
	kernel_objs = malloc(size);
	kernel_objs[0] = '\0';

	fputs(
		"ARCH ?= arm-none-eabi\n"
		"CC = $(ARCH)-gcc\n"
		"AR = $(ARCH)-ar\n"
		"RANLIB = $(ARCH)-ranlib\n\n"
		"CFLAGS =\n\n"
		"TARGETS =", fp);

	for (i = 0; i < imports->n_libs; i++) {
		fprintf(fp, " lib%s.a", imports->libs[i]->name);
	}

	fprintf(fp, "\n\n");

	for (i = 0; i < imports->n_libs; i++) {
		vita_imports_lib_t *library = imports->libs[i];
		is_special = (strcmp(KERNEL_LIBS_STUB, library->name) == 0);

		if (!is_special) {
			fprintf(fp, "%s_OBJS =", library->name);
		}

		for (j = 0; j < library->n_modules; j++) {
			vita_imports_module_t *module = library->modules[j];
			char buf[4096];
			snprintf(buf, sizeof(buf), " %s.o", module->name);
			if (is_special || module->is_kernel) {
				size_t len = strlen(buf);
				while (written + len >= size) {
					size *= 2;
					kernel_objs = realloc(kernel_objs, size);
				}
				strcat(kernel_objs, buf);
				written += len;
			} else {
				fprintf(fp, buf, module->name);
			}
		}

		if (!is_special) {
			fprintf(fp, "\n");
		}
	}

	// write kernel lib stub
	fprintf(fp, "%s_OBJS =%s\n", KERNEL_LIBS_STUB, kernel_objs);

	fputs(
		"ALL_OBJS=\n\n"
		"all: $(TARGETS)\n\n"
		"define LIBRARY_template\n"
		" $(1): $$($(1:lib%.a=%)_OBJS)\n"
		" ALL_OBJS += $$($(1:lib%.a=%)_OBJS)\n"
		"endef\n\n"
		"$(foreach library,$(TARGETS),$(eval $(call LIBRARY_template,$(library))))\n\n"
		"all: $(TARGETS)\n\n"
		"clean:\n\n"
		"\trm -f $(TARGETS) $(ALL_OBJS)\n\n"
		"$(TARGETS):\n"
		"\t$(AR) cru $@ $?\n"
		"\t$(RANLIB) $@\n\n"
		"%.o: %.S\n"
		"\t$(CC) $(CFLAGS) -c $< -o $@\n"
		, fp);

	fclose(fp);
	free(kernel_objs);

	return 1;
}

void usage()
{
	fprintf(stderr,
		"vita-libs-gen by xerpi\n"
		"usage:\n\tvita-libs-gen nids.json output-dir\n"
	);
}
